"""Play-by-play dataset definition: source columns and derived fields."""

from __future__ import annotations

import pandas as pd


SOURCE_COLUMNS = [
    "season",
    "season_type",
    "week",
    "game_id",
    "game_date",
    "home_team",
    "away_team",
    "location",
    "result",
    "home_score",
    "away_score",
    "div_game",
    "roof",
    "surface",
    "temp",
    "wind",
    "play_id",
    "drive",
    "fixed_drive",
    "fixed_drive_result",
    "qtr",
    "time",
    "quarter_seconds_remaining",
    "half_seconds_remaining",
    "game_seconds_remaining",
    "down",
    "ydstogo",
    "yardline_100",
    "yrdln",
    "goal_to_go",
    "desc",
    "play_type",
    "play_type_nfl",
    "posteam",
    "posteam_type",
    "defteam",
    "side_of_field",
    "posteam_score",
    "defteam_score",
    "score_differential",
    "posteam_score_post",
    "defteam_score_post",
    "score_differential_post",
    "total_home_score",
    "total_away_score",
    "yards_gained",
    "first_down",
    "touchdown",
    "td_team",
    "interception",
    "fumble",
    "fumble_lost",
    "sack",
    "qb_hit",
    "penalty",
    "penalty_team",
    "penalty_type",
    "penalty_yards",
    "safety",
    "tackled_for_loss",
    "third_down_converted",
    "third_down_failed",
    "fourth_down_converted",
    "fourth_down_failed",
    "rush_attempt",
    "pass_attempt",
    "complete_pass",
    "incomplete_pass",
    "qb_dropback",
    "shotgun",
    "no_huddle",
    "qb_scramble",
    "qb_kneel",
    "qb_spike",
    "pass_length",
    "pass_location",
    "air_yards",
    "yards_after_catch",
    "run_location",
    "run_gap",
    "passing_yards",
    "receiving_yards",
    "rushing_yards",
    "lateral_reception",
    "lateral_rush",
    "lateral_receiver_player_id",
    "lateral_receiver_player_name",
    "lateral_receiving_yards",
    "lateral_rusher_player_id",
    "lateral_rusher_player_name",
    "lateral_rushing_yards",
    "passer_player_id",
    "passer_player_name",
    "receiver_player_id",
    "receiver_player_name",
    "rusher_player_id",
    "rusher_player_name",
    "special_teams_play",
    "special",
    "kickoff_attempt",
    "punt_attempt",
    "field_goal_attempt",
    "extra_point_attempt",
    "two_point_attempt",
    "field_goal_result",
    "extra_point_result",
    "two_point_conv_result",
    "kick_distance",
    "return_team",
    "return_yards",
    "drive_play_count",
    "drive_time_of_possession",
    "drive_first_downs",
    "drive_inside20",
    "drive_ended_with_score",
    "drive_quarter_start",
    "drive_quarter_end",
    "drive_yards_penalized",
    "drive_start_transition",
    "drive_end_transition",
    "drive_game_clock_start",
    "drive_game_clock_end",
    "drive_start_yard_line",
    "drive_end_yard_line",
    "drive_play_id_started",
    "drive_play_id_ended",
    "epa",
    "wp",
    "wpa",
    "home_wp",
    "away_wp",
    "success",
    "ep",
    "cp",
    "cpoe",
    "xpass",
    "pass_oe",
    "qb_epa",
]

DERIVED_COLUMNS = [
    "turnover",
    "third_down_attempt",
    "red_zone_play",
    "explosive_play",
]


def add_derived_fields(play_by_play: pd.DataFrame) -> pd.DataFrame:
    play_by_play = play_by_play.sort_values(["game_id", "play_id"]).copy()

    play_by_play["turnover"] = (
        play_by_play[["interception", "fumble_lost"]].fillna(0).astype(int).sum(axis=1)
        > 0
    )
    play_by_play["third_down_attempt"] = play_by_play["down"] == 3
    play_by_play["red_zone_play"] = play_by_play["yardline_100"] <= 20
    play_by_play["explosive_play"] = (
        ((play_by_play["pass_attempt"] == 1) & (play_by_play["yards_gained"] >= 20))
        | ((play_by_play["rush_attempt"] == 1) & (play_by_play["yards_gained"] >= 10))
    )

    return play_by_play
